# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IMLCalc(object):
    def setupUi(self, IMLCalc):
        IMLCalc.setObjectName("IMLCalc")
        IMLCalc.resize(509, 424)

        self.retranslateUi(IMLCalc)
        QtCore.QMetaObject.connectSlotsByName(IMLCalc)

    def retranslateUi(self, IMLCalc):
        _translate = QtCore.QCoreApplication.translate
        IMLCalc.setWindowTitle(_translate("IMLCalc", "Form"))
